### PR TITLE
Implemented an active projects toggle (again)

### PR DESCRIPTION
**Pull request by raffazizzi**
Improves on closed PR #27 

New:
- archived projects show up again when required
- toggle respects current category selection
- introduced "reset filters" button

### CODE REVIEW

**Comment by raffazizzi** [comment]
Made a hard reset on this branch because I changed strategy altogether. Now the active switch is implemented as a proper category. This comes with pros and and small con:

PROS:
- filtering is simple and handled by existing code
- category views can be overridden, so this "active" category implements its own template that we can style as we like (ie if we want to make into a nice big switch), [see here](https://github.com/umd-mith/mith-research-explorer/blob/8d8e38996f684510cecee10611ca8ecc5a63e160/src/js/templates/activeProject-tpl.js).

CON:
The category is a boolean, but it can't be treated as such because other categories are all based on string comparisons. So the category is hacked into being a string. Hey, it works.
See [here](https://github.com/umd-mith/mith-research-explorer/blob/8d8e38996f684510cecee10611ca8ecc5a63e160/src/js/data/model-project.js#L11) and [here](https://github.com/umd-mith/mith-research-explorer/blob/8d8e38996f684510cecee10611ca8ecc5a63e160/src/js/views/app-view.js#L78).

HTML changes for @kirstenkeister to note:
- https://github.com/umd-mith/mith-research-explorer/commit/3307f18f5b508839f41883d853deb1ae3d6a4fae
- https://github.com/umd-mith/mith-research-explorer/commit/03fb9e47634476753c870d43ca294f5f24e6db8a
- the new category [template](https://github.com/umd-mith/mith-research-explorer/blob/8d8e38996f684510cecee10611ca8ecc5a63e160/src/js/templates/activeProject-tpl.js)

**Comment by trevormunoz** [comment]
I think I am ok with merging this, pace #30 and the small hack to handle active projects.

**Comment by raffazizzi** [comment]
@trevormunoz that was an actual bug that I introduced on years, so they weren't working at all. Should be fine now, it was a quick fix. Can you give it another test ride? (hopefully the last one...) Thanks.

**Comment by trevormunoz** [comment]
Works now!

**Pull request merged**
