### PR TITLE
Implemented an active projects toggle

### PR DESCRIPTION
**Pull request by raffazizzi**

### CODE REVIEW

**Comment by trevormunoz** [comment]
NB: I problem introduced a small merge conflict with #26 by making a small change to the HTML

**Comment by trevormunoz** [comment]
More substantively, this limits the visible project to the 8 or 9 active ones when I click the toggle box, however, I'm then unable to get other projects to come back either by 1) unchecking the box; or 2) clicking "SHOW ALL" (don't know if this was ever meant to happen).

I have to reload the page to get non-active projects back.

**Comment by raffazizzi** [comment]
Well that's annoying - will look into it. 

I didn't think about the behavior for "show all", what do you and @kirstenkeister think? It can either
- show all projects, but respect the active/non-active selection
- show all projects including non-active (so it's equivalent to refreshing the page)

I can see value in both approaches, but I would lean towards the second and maybe rename it to "reset filters" or something like that.

**Comment by raffazizzi** [comment]
Please feel free to reply to the comment above here, but I'm closing this PR. Will re-open a new one from a cleaner branch.

**Comment by trevormunoz** [comment]
I favor option 2 w/label "reset filters"

**Pull request closed without merging**
